In [2]:
import pandas as pd
import numpy as np
import googlemaps
from datetime import datetime

In [3]:
df1 = pd.read_csv('review.csv')

In [5]:
df1.head(10)

,id,title_id,text,author,score,pub_date
0,1,1,Ставлю десять звёзд!\n...Эти голоса были чище ...,100,10,2019-09-24T21:08:21.567Z
1,2,1,Не привыкай\n«Эти стены имеют одно свойство: с...,101,10,2019-09-24T21:08:21.567Z
2,3,2,"Фильм, разобранный на цитаты, достоин высшей о...",102,10,2019-09-24T21:08:21.567Z
3,4,2,"Жестокий, жестокий, жестокий мир, не о таком м...",103,1,2019-09-24T21:08:21.567Z
4,5,2,"Это мои соседи! Ставлю три звезды за то, что о...",104,3,2019-09-24T21:08:21.567Z
5,16,3,"Сходила в кино, решила написать: драйв и огонь...",100,7,2019-09-24T21:08:21.567Z
6,17,3,"Смотрел, не отрываясь, хочу описать свои впеча...",101,8,2019-09-24T21:08:21.567Z
7,18,4,"Скачал, посмотрел, думаю, что актёры так себе,...",102,8,2019-09-24T21:08:21.567Z
8,19,4,"Посмотрел. По моему мнению, актёры так себе, н...",103,10,2019-09-24T21:08:21.567Z
9,6,5,"Всё, как в разных языках программирования! В о...",100,8,2019-09-24T21:08:21.567Z